# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint
# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# imports city inf as a data frame
city_df = pd.read_csv("output_data/city.csv")
city_df.head()

,City,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
0,Kismayo,-0.36,42.55,298.53,74,100,9.30,SO,1595214778
1,Latung,5.50,120.88,302.00,76,9,2.99,PH,1595195446
2,Dikson,73.51,80.55,278.64,91,31,5.22,RU,0
3,Saint Paul Harbor,57.79,-152.41,288.15,72,1,5.10,US,1595252515
4,Jamestown,42.10,-79.24,298.15,69,75,5.70,US,1595239136

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# converts city temp from k to f
city_df["Temperature"] = (9/5) * (city_df["Temperature"] - 273) + 32

In [5]:
# creates a heatmap of the cities based on humidity
gmaps.configure(api_key=g_key)
locations = city_df[["Latitude", "Longitude"]]
fig = gmaps.figure()
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}

heat_layer = gmaps.heatmap_layer(locations, weights=city_df["Humidity"], 
                                 dissipating=False, max_intensity=city_df["Humidity"].max(),
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
# creates a reduced list of cities based on ideal temperature specifcations 
reduced_city_df = city_df.loc[(city_df["Temperature"] < 80) & (city_df["Temperature"] > 70) & (city_df["Wind Speed"] < 10) & (city_df["Cloudiness"] == 0)]
reduced_city_df

,City,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
7,Ponta do Sol,32.67,-17.10,74.264,57,0,0.47,PT,1595225673
100,Arraial do Cabo,-22.97,-42.03,79.070,61,0,7.20,BR,1595237219
106,East London,-33.02,27.91,73.670,25,0,2.60,ZA,1595221603
110,Namwala,-15.75,26.44,74.210,29,0,3.66,ZM,1595220063
198,Opuwo,-18.06,13.84,78.746,17,0,4.70,NaN,1595223312
213,Chissamba,-12.17,17.33,70.070,22,0,4.60,AO,1595221908
227,Muros,42.78,-9.06,78.278,61,0,7.60,ES,1595222158
232,Maamba,-17.37,27.15,73.418,27,0,2.32,ZM,1595220050
240,Bethanien,-26.50,17.16,76.892,15,0,6.47,NaN,1595223401
252,Cidreira,-30.18,-50.21,73.184,67,0,1.42,BR,1595239992
288,Mezen',65.85,44.24,77.090,36,0,2.06,RU,1595199872
330,Jiaozhou,36.28,120.00,75.272,88,0,1.00,CN,1595192243
345,Shakawe,-18.37,21.85,77.522,18,0,3.63,BW,1595221421
367,Darnah,32.77,22.64,78.944,64,0,9.58,LY,1595216118
406,Saldanha,-33.01,17.94,70.070,52,0,2.60,ZA,1595223993
410,Guerrero Negro,27.98,-114.06,73.112,67,0,1.35,MX,1595249549
439,San Vicente,-26.62,-54.13,74.714,51,0,3.11,AR,1595240519
487,Morondava,-20.28,44.28,72.446,67,0,4.78,MG,1595216230
533,Henties Bay,-22.12,14.28,77.774,23,0,4.13,NaN,1595223619

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
# creates a dictionary for storing hotel information 
hotel_dict = {
    "Hotel Name": [],
    "City": [],
    "Country": [],
    "Lat": [],
    "Lng": []
}
# iterates through the cities in the reduced city data frame
for city in reduced_city_df.iterrows():
    
    target_coordinates = f"{city[1]['Latitude']},{city[1]['Longitude']}"
    target_radius = 5000
    target_type = "hotel"
  
 
    # set up a parameters dictionary
    params = {
        "location": target_coordinates,
        "radius": target_radius,
        "type": target_type,
        "key": g_key
    }
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # searchs fro hotels in the reare based on above parameters 
    hotel_json = requests.get(base_url, params=params).json()
    # Extracts info from the first hotel thats returned from the requests
    hotel_dict["Hotel Name"].append(hotel_json['results'][1]['name'])
    hotel_dict["City"].append(city[1]["City"])
    hotel_dict["Country"].append(city[1]["Country"])
    hotel_dict["Lat"].append(hotel_json['results'][1]['geometry']['location']['lat'])
    hotel_dict["Lng"].append(hotel_json['results'][1]['geometry']['location']['lng'])

In [8]:
# returns data frame of hotel info 
hotel_df = pd.DataFrame(hotel_dict)
hotel_df

,Hotel Name,City,Country,Lat,Lng
0,Hotel do Campo,Ponta do Sol,PT,32.676959,-17.066139
1,Pousada Porto Praia,Arraial do Cabo,BR,-22.977949,-42.023863
2,Tu Casa,East London,ZA,-32.985159,27.923570
3,MOOKS FARM,Namwala,ZM,-15.748528,26.440453
4,PEP Opuwo,Opuwo,NaN,-18.060050,13.841237
5,Hospital de Chissamba,Chissamba,AO,-12.159893,17.324899
6,BBVA,Muros,ES,42.774744,-9.057182
7,Turbine Building of Maamba collieries . power ...,Maamba,ZM,-17.352475,27.186214
8,Bethanie Guesthouse,Bethanien,NaN,-26.501838,17.161983
9,Diego Imóveis,Cidreira,BR,-30.161955,-50.202134
10,Rosgosstrakh,Mezen',RU,65.842867,44.246820
11,Gao Fenghan's Memorial Hall,Jiaozhou,CN,36.254814,120.012554
12,PEP Shakawe,Shakawe,BW,-18.360949,21.843451
13,Hamza Mosque,Darnah,LY,32.750756,22.655010
14,Blue Bay Lodge,Saldanha,ZA,-32.995413,17.973140
15,Bimbo,Guerrero Negro,MX,27.969271,-114.039894
16,Banco Macro Sucursal 13 San Pedro,San Vicente,AR,-26.624869,-54.113204
17,La Case Bambou,Morondava,MG,-20.297942,44.269427
18,Fishermans Guest House,Henties Bay,NaN,-22.133595,14.291068

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [10]:
# Adds marker layer ontop of heat map that represents hotel locations 
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
# Adds the layer to the map
fig.add_layer(markers)
# Displays figure
fig

Figure(layout=FigureLayout(height='420px'))